# Generated by Django 2.2.16 on 2022-10-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220915_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(help_text='Краткое описание объединения записей', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='идентификатор группы', max_length=200, unique=True, verbose_name='ID группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='Подборка записей одной темы', max_length=200, verbose_name='заголовок'),
        ),
    ]
